### ISSUE TITLE
Unknown function: which_key#register

### ISSUE THREAD

**Issue by Quoteme** [AckslD/nvim-whichkey-setup.lua#15]
Error:
```
Error detected while processing /nix/store/8wlldfkb4898n9vzl6rw0pb4df3ffcgk-init.vim:
line  100:
E5108: Error executing lua Vim:E117: Unknown function: which_key#register
```

System nixos 21.11

my init.vim looks like regarding whichkey:
```
" WhichKey
lua << EOF
require("which-key").setup {
}
EOF

" WhichKeySetup
lua << EOF
local wk = require('whichkey_setup')
local keymap = {
	l = {
		':exec &conceallevel ? "set conceallevel=0" : "set conceallevel=1"',
		'toggle conceal'
		},
}
wk.register_keymap('leader', keymap)
EOF
```

I installed nvim-whichkey-setup using the nixos package manager. This loads the plugins using vims build in package manager. Does anyone else have this problem and is it caused by nvim-whichkey-setup or nixos?

Also, can I put something into my init.vim so that when nvim-whichkey-setup asks for `which_key#register`, I can instead point it to some other function? `WhichKey` is defined but `which_key` strangely is not.

**Comment by Quoteme** [comment]
Ok sorry, my bad.
It turns out I installed https://github.com/folke/which-key.nvim instead of https://github.com/liuchengxu/vim-which-key

**Comment by AckslD** [comment]
Hi @Quoteme! Good to hear that it works. Folkes whichkey for nvim was made after I did this and I'd recommend you to use that instead of this nowadays :)
