### ISSUE TITLE
Visual maps fail with "[which-key] Fail to execute, no such mapping"

### ISSUE THREAD

**Issue by thisisrandy** [AckslD/nvim-whichkey-setup.lua#17]
#### Minimal `init.vim`

Assumes `vim-plug` is installed and `:PlugInstall` has been run:

```vim
call plug#begin('~/.local/share/nvim/plugged')
Plug 'liuchengxu/vim-which-key'
Plug 'AckslD/nvim-whichkey-setup.lua'
call plug#end()

set timeoutlen=500
let mapleader=" "

lua<<EOF
local wk = require('whichkey_setup')

local visual_keymap = {
        b = {'"_d', '[b]lackhole-delete'}
}

wk.register_keymap('leader', visual_keymap, { mode = 'v', silent = false })
EOF
```

#### Expected

Pressing `<leader>`, pausing to wait for the `which-key` menu to appear, and then pressing `b` should delete the selected text to the blackhole register (`_`).

#### Actual

An error is issue with the text "[which-key] Fail to execute, no such mapping".

#### Other info

Pressing `<leader>b` before `timeoutlen` is exhausted has the expected behavior. Indeed, the output of `:verbose vmap <leader>b` is

```
v  <Space>     * :<C-U> :WhichKey "<VisualBindings>"<CR>
        Last set from Lua line 16
```

, so the plugin correctly sets the mapping but somehow fails to fully register it with `which-key`.

**Comment by AckslD** [comment]
Hi @thisisrandy! Nowadays I would recommend you to use https://github.com/folke/which-key.nvim instead :)

**Comment by thisisrandy** [comment]
Oh, that is quite a bit shinier, isn't it? Thanks for the tip! I just tried the same idea with that plugin, and it works as expected.

**Comment by AckslD** [comment]
Glad to hear! :)
