### ISSUE TITLE
set (<Plug><command>) not able to set

### ISSUE THREAD

**Issue by lalitmee** [AckslD/nvim-whichkey-setup.lua#2]
I have some commands which start with `<Plug>(git-messenger)`. I am not able to run these commands.

for example:

```lua
    g = {
      name = '+gists',
      c = { '<Plug>fov_new', 'create-new-gist' },
      l = { '<Plug>fov_list', 'list-gists' },
      u = { '<Plug>fov_update', 'update-gist' },
      v = { '<Plug>fov_visual_new', 'create-new-from-visual' }
    },
```

Am I missing something here? :thinking:

**Comment by AckslD** [comment]
@lalitmee By default noremap is true so you'll need to pass `{noremap = false}` when registering to be able to use the `<Plug>`-mappings.

**Comment by lalitmee** [comment]
Got it. It means I will have to create another variable for `plug keymaps` and then register those to `noremap = false`.

**Comment by AckslD** [comment]
@lalitmee closing this issue. Let me know if you still have issues and if so reopen the issue

**Comment by lalitmee** [comment]
No, I solved it by doing what you told me to do. Thanks for this awesome tool. It also improves somethings which I wanted in the vim-which-key.
