### ISSUE TITLE
which-key shows keys even when they are not bound to current buffer

### ISSUE THREAD

**Issue by famiu** [AckslD/nvim-whichkey-setup.lua#4]
So I use Neovim's built-in LSP, I have set it up so that everytime an LSP server is attached to a buffer, it also assigns a set of keybindings and the which key descriptions for them. When I'm using a buffer with LSP, everything works as intended. However, when I open a buffer without LSP, which-key still shows them, even though they aren't bound anymore.

Buffer with LSP:
![image](https://user-images.githubusercontent.com/29580810/113469106-bc368300-946c-11eb-8b44-808502050df8.png)

Buffer without LSP:
![image](https://user-images.githubusercontent.com/29580810/113469116-d5d7ca80-946c-11eb-80bf-93656633c5f5.png)

I also used :map to see if they are somehow bound to those keys, but didn't find any bindings. So the issue seems to be on which-key

**Comment by AckslD** [comment]
Think the same as #1

**Comment by famiu** [comment]
Should I close it, then?

**Comment by AckslD** [comment]
I'll close it since it is easier to keep track of the issue in one place. However, if I misunderstood and your issue is different, feel free to open this again.
