### ISSUE TITLE
Hide status line

### ISSUE THREAD

**Issue by 1612492** [AckslD/nvim-whichkey-setup.lua#5]
Can you add config for this?

```vim
autocmd! FileType which_key
autocmd  FileType which_key set laststatus=0 noshowmode noruler
  \| autocmd BufLeave <buffer> set laststatus=2 showmode ruler
```

**Comment by 1612492** [comment]
Hi, I'm a newbie from `lua` :)
I am trying to add the below config but when I leave the which_key buffer, it doesn't clear the message.

![image](https://user-images.githubusercontent.com/39008689/113910305-e1c3e380-9802-11eb-8f8e-a57340d86428.png)
![image](https://user-images.githubusercontent.com/39008689/113910597-38312200-9803-11eb-8d8a-cee7b393e4db.png)

**Comment by AckslD** [comment]
Hey @1612492! I added an option to setup these autocommands to hide the status line. You can configure it by calling:
```lua
require("whichkey_setup").config{
    hide_statusline = true,
}
```
somewhere in your config.

For more details see the [updated README](https://github.com/AckslD/nvim-whichkey-setup.lua#config) and #6 .

Feel free to let me know if this does not work for you!
